### ISSUE TITLE
pick up band name and send to event hub

### ISSUE THREAD

**Issue by davidgristwood** [BandOnTheRun/ms-band-azure#4]
var serviceNamespace = "bandontherun-ns";
            var hubName = "msbands";
            var url = string.Format("{0}/publishers/{1}/messages", hubName, deviceTelemetry.DeviceId);

this seems to be hard coded

```
    private static DeviceTelemetry _data = new DeviceTelemetry { DeviceId = "dxband" };
```

**Comment by peted70** [comment]
Has since been fixed
